### PR TITLE
fixed nine bits processing, updated reset code behaviour

### LINKED ISSUE #5: compression with 9 bits don't work
it simply doesn't work (no 8-codes block flush after the clear code?):
$ compress -cb9 /usr/bin/compress >/tmp/test.Z
$ compress -dc /tmp/test.Z
insize:7901 posbits:0 inbuf:00 0A F7 23 CC (0)
uncompress: corrupt input
$ gzip -tv /tmp/test.Z
gzip: /tmp/correct.Z: corrupt input.

and it is not working for a long time (at least 12 years):
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=220820

the debian proposed patch (using at least 10 bits) would break the Single UNIX Specification, Version 4 (IEEE Std 1003.1) as 9 <= bits <= 14:
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/compress.html

if the bug cannot be resolved, a note should be added, like the one present in the debian package readme:
"If you create files using -b9 (maxbits of 9), your file is probably corrupted, and you will only be able to recover parts of it."

ciao!

### PR DESCRIPTION
**Pull request by andrew-aladev**
Closes #5.

Please review small pr, it fixes nine bits processing. The problem is that `extcode` and `maxcode` together with `n_bits` were not properly initialized and reset. I've added code in the same style as code around.

We may create macro like `reset_n_bits_for_compressor` and `reset_n_bits_for_decompressor` instead of just copying code twice.

### CODE REVIEW

File: compress.c [hunk 1]
```diff
@@ -1250,7 +1250,10 @@ compress(fdin, fdout)
 
 		ratio = 0;
 		checkpoint = CHECK_GAP;
-		extcode = MAXCODE(n_bits = INIT_BITS)+1;
+		if ((n_bits = INIT_BITS) < maxbits)
+			extcode = MAXCODE(n_bits)+1;
```
Comment (vapier) [inline compress.c:1254]: seems like it'd be a little easier to read if it were:

```c
extcode = MAXCODE(n_bits);
if (n_bits < maxbits)
  extcode += 1
```

wdyt ?

**Review by vapier — CHANGES_REQUESTED** [review]

File: compress.c (hunk 1 above)
Comment (andrew-aladev) [reply compress.c:1254]: Sure, I will update it today, thank you.

File: compress.c [hunk 2]
```diff
@@ -1250,7 +1250,10 @@ compress(fdin, fdout)
 
 		ratio = 0;
 		checkpoint = CHECK_GAP;
-		extcode = MAXCODE(n_bits = INIT_BITS)+1;
+		if ((n_bits = INIT_BITS) < maxbits)
```
[the remark this answers is not in the document]
Comment (andrew-aladev) [reply compress.c:1253]: Sure, I will update it today.

**Review by vapier — APPROVED** [review]

**Comment by vapier** [comment]
> We may create macro like `reset_n_bits_for_compressor` and `reset_n_bits_for_decompressor` instead of just copying code twice.

i just noticed this suggestion.  if you want to do that, sounds good to me.

**Comment by andrew-aladev** [comment]
Added small macro for reset `n_bits`, please review.

**Comment by vapier** [comment]
thanks!

**Comment by N-R-K** [comment]
This seems to break decoding compressed file produced by older versions.

```console
$ seq 1000 | sha512sum
33d2768487a466e69c6399cdadc8c4dbfb0999073c356be48e1b6031f0f8fdbe57c567d9f08a1d46a892efc5a670fb16fd699b4bf74d3cca120d39b1e8bfb4e3  -
$ seq 1000 | ./compress-3.0 -b9 | ./compress-5.0 -d | sha512sum
Compression: 39.84%
33d2768487a466e69c6399cdadc8c4dbfb0999073c356be48e1b6031f0f8fdbe57c567d9f08a1d46a892efc5a670fb16fd699b4bf74d3cca120d39b1e8bfb4e3  -
```

ncompress v5.0 can decompress the above sequence produced by ncompress v3.0 (so can `pigz` and `gnu gzip`).

But if I use ncompress `main` branch (commit c576364), it doesn't decompress correctly:

```console
$ seq 1000 | ./compress-3.0 -b9 | ./compress-main -d | sha512sum
Compression: 39.84%
insize:470 posbits:0 inbuf:43 CD 39 F4 9C (0)
uncompress: corrupt input
```

**Comment by N-R-K** [comment]
Also something interesting from [pigz.c#L3683](https://github.com/madler/pigz/blob/fe4894f57739e3039a2ffc2a2a360d35e19bacbe/pigz.c#L3683-L3684)

```c
    if (max == 9)  // 9 doesn't really mean 9
        max = 10;
```

**Comment by N-R-K** [comment]
Okay, I see what's going on. In version 4.1 and below, the `n_bits` increment logic is broken when `-b 9`.

https://github.com/vapier/ncompress/blob/fb52189600278fdaf6b101caf180e5ee4b0e0ecb/compress.c#L1075-L1079

It increments first and *then* checks for `== maxbit`. `n_bits` always starts off with 9, and so when `maxbit` is 9, it will just increment `n_bits` above 9 anyways.



v4.2 seems to have fixed this particular bug. (Though `-b 9` is still broken in v4.2 but for other reasons outlined in #5).
